// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/index.qtpl:1
package views

//line views/index.qtpl:1
import "github.com/Bios-Marcel/testing_golang_stuff/data"

//line views/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/index.qtpl:3
func StreamIndex(qw422016 *qt422016.Writer, user *data.User) {
//line views/index.qtpl:3
	qw422016.N().S(`
<html>
    `)
//line views/index.qtpl:5
	if user == nil {
//line views/index.qtpl:5
		qw422016.N().S(`
        <a href="/register">Register</a>
        <a href="/login">Login</a>
    `)
//line views/index.qtpl:8
	} else {
//line views/index.qtpl:8
		qw422016.N().S(`
        Hello `)
//line views/index.qtpl:9
		qw422016.E().S(user.GetDisplayName())
//line views/index.qtpl:9
		qw422016.N().S(`
        <form action="/logout" method="POST">
            <input type="submit" value="Logout" />
        </form>
    `)
//line views/index.qtpl:13
	}
//line views/index.qtpl:13
	qw422016.N().S(` 
</html>
`)
//line views/index.qtpl:15
}

//line views/index.qtpl:15
func WriteIndex(qq422016 qtio422016.Writer, user *data.User) {
//line views/index.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/index.qtpl:15
	StreamIndex(qw422016, user)
//line views/index.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line views/index.qtpl:15
}

//line views/index.qtpl:15
func Index(user *data.User) string {
//line views/index.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line views/index.qtpl:15
	WriteIndex(qb422016, user)
//line views/index.qtpl:15
	qs422016 := string(qb422016.B)
//line views/index.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line views/index.qtpl:15
	return qs422016
//line views/index.qtpl:15
}
