// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/login.qtpl:1
package views

//line views/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/login.qtpl:1
func StreamLogin(qw422016 *qt422016.Writer, failed bool) {
//line views/login.qtpl:1
	qw422016.N().S(`
<html>
    <head>
        <style>
            .basic-form {
                display: grid;
                grid-template-columns: max-content auto;
                grid-template-rows: repeat(min-content);
                column-gap: 1rem;
                row-gap: 0.5rem;
            }
        </style>
    </head>
    <body>
        <form action="/login" method="POST">
            `)
//line views/login.qtpl:16
	if failed {
//line views/login.qtpl:16
		qw422016.N().S(`
            <b>E-Mail or password were incorrect. Don't give up!</b>
            `)
//line views/login.qtpl:18
	}
//line views/login.qtpl:18
	qw422016.N().S(`
            <div class="basic-form">
                <label for="email">E-Mail</label>
                <input type="email" name="email"></input>
                <label for="password">Password</label>
                <input type="password" name="password"></input>
            </div>

            <button type="submit">Login</button>
        </form>
    </body>
</html>
`)
//line views/login.qtpl:30
}

//line views/login.qtpl:30
func WriteLogin(qq422016 qtio422016.Writer, failed bool) {
//line views/login.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/login.qtpl:30
	StreamLogin(qw422016, failed)
//line views/login.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line views/login.qtpl:30
}

//line views/login.qtpl:30
func Login(failed bool) string {
//line views/login.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line views/login.qtpl:30
	WriteLogin(qb422016, failed)
//line views/login.qtpl:30
	qs422016 := string(qb422016.B)
//line views/login.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line views/login.qtpl:30
	return qs422016
//line views/login.qtpl:30
}
