// Code generated by qtc from "register.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/register.qtpl:1
package views

//line views/register.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/register.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/register.qtpl:1
func StreamRegister(qw422016 *qt422016.Writer) {
//line views/register.qtpl:1
	qw422016.N().S(`
<html>
    <head>
        <style>
            .basic-form {
                display: grid;
                grid-template-columns: max-content auto;
                grid-template-rows: repeat(min-content);
                column-gap: 1rem;
                row-gap: 0.5rem;
            }
        </style>
    </head>
    <body>
        <form action="/register" method="POST">
            <div class="basic-form">
                <label for="display_name">Display name</label>
                <input type="text" name="display_name"></input>
                <label for="email">E-Mail</label>
                <input type="email" name="email"></input>
                <label for="password">Password</label>
                <input type="password" name="password"></input>
            </div>

            <button type="submit">Register</button>
        </form>
    </body>
</html>
`)
//line views/register.qtpl:29
}

//line views/register.qtpl:29
func WriteRegister(qq422016 qtio422016.Writer) {
//line views/register.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/register.qtpl:29
	StreamRegister(qw422016)
//line views/register.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line views/register.qtpl:29
}

//line views/register.qtpl:29
func Register() string {
//line views/register.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line views/register.qtpl:29
	WriteRegister(qb422016)
//line views/register.qtpl:29
	qs422016 := string(qb422016.B)
//line views/register.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line views/register.qtpl:29
	return qs422016
//line views/register.qtpl:29
}
